config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"

  resources :rooms
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates :start, :end, presence: :true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  validates :name, :capacity, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was created successfully!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was updated successfully!" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully removed!" }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:room_id, :user_id, :start, :end, :purpose)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was created successfully!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was updated successfully!" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully removed!" }
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :capacity)
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_booking.html.erb
<ul>
  <li>Room: <%= link_to booking.room.name, booking.room %></li>
  <li>Start: <%= booking.start %></li>
  <li>End: <%= booking.end %></li>
  <li>Purpose: <%= booking.purpose %></li>
</ul>

app/views/bookings/_form.html.erb
<h1>List of Bookings</h1>

<%= form_with(model: booking) do |f| %>
  <% if booking.errors.any? %>
   <div style="color: red">
    <h2><%= pluralize(booking.errors.count, 'error') %> prohibited the booking from saving!</h2>
    <ul>
    <% booking.errors.each do |e| %>
      <li><%= e.full_message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :start, style: "display: block" %>
    <%= f.datetime_field :start %>
  </div>
  <div>
    <%= f.label :end, style: "display: block" %>
    <%= f.datetime_field :end %>
  </div>
  <div>
    <%= f.label :purpose, style: "display: block" %>
    <%= f.text_field :purpose %>
  </div>
  <div>
    <%= f.label :room, style: "display: block" %>
    <%= f.collection_select :room_id, Room.all, :id, :name  %>
  </div>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id  %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1> Edit Booking </h1>

<%= render 'form', booking: @booking %>

app/views/bookings/index.html.erb
<h2>List of Bookings</h2>

<%= render @bookings %>

<%= link_to "Create Booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1> New Booking </h1>

<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<%= render @booking %>
<%= link_to "Edit Booking", edit_booking_path %>
<%= button_to "Remove this Booking", @booking, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= link_to "Rooms", rooms_path %>
    <%= link_to "Bookings", bookings_path %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to "Log in", new_user_session_path %>
  <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |f| %>
  <% if room.errors.any? %>
   <div style="color: red">
    <h2><%= pluralize(room.errors.count, 'error') %> prohibited the room from saving!</h2>
    <ul>
    <% room.errors.each do |e| %>
      <li><%= e.full_message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, style: "display: block" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :capacity, style: "display: block" %>
    <%= f.number_field :capacity %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<ul>
  <li><%= link_to room.name, room %></li>
  <li><%= room.capacity %></li>
</ul>

app/views/rooms/edit.html.erb
<h1> Edit Room </h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<h2>List of Rooms</h2>

<%= render @rooms %>

<%= link_to "Create Room", new_room_path %>

app/views/rooms/new.html.erb
<h1> New Room </h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<h2><%= @room.name %></h2>
<h3>Capacity: <%= @room.capacity %></h3>
  <strong>Current Bookings:</strong>
  </br>
  <ul>
    <% @room.bookings.each do |booking| %>
      <li> Booking Start: <%= booking.start %></li>
      <li> Booking End: <%= booking.end %></li>
      <li> Booking Purpose: <%= booking.purpose ? booking.purpose : 'N/A' %></li>
      <li> Booking: <%= link_to 'Booking', booking %></li>
      </br>
    <% end %>
  </ul>
<%= link_to "Edit Room", edit_room_path %>
<%= button_to "Remove this Room", @room, method: :delete %>